# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d7126b80c6578aa8ee603fb9f99b2e65f645095f8a5a7f3e4ccb2335905d9ff5cfe6e36886d38dc7754f1eada818014d73efef92e071a6f969a8ebe6ab99baf8

test:
  secret_key_base: 549addff4de1e705dc4c4f2321dbb214374c5949a371182eaac003a95d8d1ea94baaefd51b0d23ca68767c47c00656ab0c9d5406ad910ccf32ddda2ff0a2c4ed

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
